server.port=8081
springdoc.api-docs.path=/api/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.application.name=medvida-api

spring.datasource.url=jdbc:postgresql://localhost:5432/medvida_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update 
# Usar esse de cima na aplicação pra ir atualiando sempre que iniciar a plicação

# spring.jpa.hibernate.ddl-auto=create-drop 
# Utilizado para alguns problemas de id que estavam acontecendo.
# Porem se quiser usar para limpar dados extras adicionados sem ser os adicionais, so comentar o update e descomentar o create-drop.

spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect